---
- name: Configure common system
  hosts:
    - docker
    - erp
  become: true
  roles:
    - update
    - common
    - docker

- name: Configure Docker host
  hosts: docker
  become: true
  roles:
    - compose
